name: Install Google Chrome on Ubuntu Server

on:
  workflow_dispatch:
    inputs:
      server:
        description: "Target server hostname or IP"
        required: true
      user:
        description: "SSH username"
        required: true
jobs:
  install-chrome:
    runs-on: self-hosted
    steps:
      - name: Install Google Chrome remotely
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            set -e
            echo ">>> Updating apt and installing dependencies..."
            sudo apt-get update -y
            sudo apt-get install -y wget gnupg2 apt-transport-https software-properties-common

            echo ">>> Adding Google signing key and repository..."
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub \
              | sudo gpg --dearmor -o /usr/share/keyrings/google-linux.gpg
            echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux.gpg] \
              http://dl.google.com/linux/chrome/deb/ stable main" \
              | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update -y

            echo ">>> Installing Google Chrome..."
            sudo apt-get install -y google-chrome-stable

            echo ">>> Verifying installation..."
            google-chrome --version || echo "Chrome installed but not in PATH."
