name: Deploy WebUI.php from DevOps-Project to server

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: "Target server IP"
        required: true
      server_user:
        description: "Target server username"
        required: true
      repo_b_branch:
        description: "Branch of DevOps-Project to deploy"
        required: false
        default: main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo A (current repo:TestPublic)
        uses: actions/checkout@v3

      - name: Checkout Repo B (DevOps-Project via deploy key)
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/DevOps-Project
          ssh-key: ${{ secrets.GH_DEPLOY_KEY }}
          ref: ${{ github.event.inputs.repo_b_branch }}
          path: repo-b
          persist-credentials: false
          ssh-strict: false

      - name: Debug (list files from Repo B)
        run: ls -l repo-b

      - name: Verify webui.php exists
        run: test -f repo-b/webui.php || (echo "webui.php not found!" && exit 1)

      - name: Test SSH connection to server
        run: |
          printf "%s\n" "${{ secrets.SERVER_SSH_KEY }}" > $RUNNER_TEMP/id_rsa
          chmod 600 $RUNNER_TEMP/id_rsa
          ssh -o StrictHostKeyChecking=no -i $RUNNER_TEMP/id_rsa ${{ github.event.inputs.server_user }}@${{ github.event.inputs.server_ip }} "echo Connected OK"
          rm -f $RUNNER_TEMP/id_rsa

      - name: Copy webui.php from Repo B to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ github.event.inputs.server_ip }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "repo-b/webui.php"
          target: ${{ secrets.TARGET_PATH }}
          overwrite: true
          debug: true
